version: '3'
services:
     webapp:
          build: .
          container_name: webapp
          command: npm start
          ports:
               - '3000:3000'
          environment:
               PORT: 3000

          volumes:
               - .:/usr/src/app

          restart: always
volumes:
     alldata:
